# general parameters
trial_path:             logs
trial_name:             reinforce_frozenlake_noise_model
wandb:                  True
project_name:           cleanqrl

# ray tune parameters
ray_local_mode:         False
num_cpus:               20
num_gpus:               0s
num_samples:            5
cpus_per_worker:        1
gpus_per_worker:        0

# environment parameters
env_id:         CustomMazeEnv
maze_name:      neumann_c
state_encoding: binary
P:              -200
R:              200
N:              -10
n:              3

# algorithm parameters
agent:              REINFORCE_quantum_discrete_state_custom_maze
total_timesteps:    20000
lr_input_scaling:   0.025  
lr_weights:         0.025 
lr_output_scaling:  0.1  
num_envs:           1
seed:               42
gamma:              0.95
num_qubits:         5
num_layers:         5
device:             lightning.qubit
diff_method:        adjoint
cuda:               False
save_model:         False
